name: Build and Push for Server

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  DIST_DIR: public
  TARGET_DIR: server
  IMAGE_NAME: server
  DOCKER_FILE: server/Dockerfile
  DOCKER_REGISTRY: docker.pkg.github.com

jobs:
  push:
    # ソースコード一式を Docker コンテナーに封入して GitHub Packages にプッシュする
    name: Push docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Login registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build --file $DOCKER_FILE --tag $IMAGE_NAME .

      - name: Push image
        run: |
          IMAGE_ID=$DOCKER_REGISTRY/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          IMAGE_VERSION=latest

          echo "IMAGE_ID:" $IMAGE_ID
          echo "IMAGE_VERSION:" =$IMAGE_VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION

  deploy:
    # GitHub Packages にプッシュした最新のイメージをデプロイ先に通知する
    name: Deploy image
    runs-on: ubuntu-latest
    needs: push

    steps:
      # 開発用
      - name: Send HTTP-POST to Webhook-URL for Develop
        if: github.ref != 'refs/heads/master'
        run: curl -X POST -L ${{ secrets.SERVER_DEVELOP_DOCKER_WEBHOOK_URL }}

      # 本番用
      - name: Send HTTP-POST to Webhook-URL for Production
        if: github.ref == 'refs/heads/master'
        run: curl -X POST -L ${{ secrets.SERVER_PRODUCTION_DOCKER_WEBHOOK_URL }}
